# Generated by Django 3.0.5 on 2020-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='chip_number',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='numer chip'),
        ),
    ]
