# Generated by Django 3.0.5 on 2020-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_auto_20200717_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='chip_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='numer chip'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identification_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='identyfikator'),
        ),
    ]
