# Generated by Django 3.0.5 on 2020-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20200717_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='additional_information',
            field=models.TextField(blank=True, default='', verbose_name='dodatkowe informacje'),
        ),
    ]
