# Generated by Django 3.0.5 on 2020-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0004_auto_20200718_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Data rejestracji'),
        ),
    ]
