# Generated by Django 3.0.5 on 2020-07-18 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_animal_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.PositiveIntegerField(help_text='Wprowadź przybliżony wiek', validators=[django.core.validators.MinValueValidator(0, 'Wiek nie może być <= 0'), django.core.validators.MaxValueValidator(40, 'Wiek nie może być większy od 30')], verbose_name='przybliżony wiek'),
        ),
    ]
