# Generated by Django 3.0.5 on 2020-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0006_auto_20200718_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='additional_information',
            field=models.TextField(blank=True, default='Ten piesek/kotek jeszcze nie ma opisu. Jedno wiemy napewno - będzie super szczęśliwy w nowej rodzinie', verbose_name='dodatkowe informacje'),
        ),
    ]
