# Generated by Django 3.0.5 on 2020-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0007_auto_20200718_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
