# Generated by Django 3.0.5 on 2020-08-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0010_auto_20200812_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalgallery',
            old_name='photo',
            new_name='photos',
        ),
    ]
