# Generated by Django 3.0.5 on 2020-09-24 17:59

import django.db.models.deletion
from django.db import migrations, models

import shelter.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0011_auto_20200812_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalgallery',
            options={'verbose_name': 'Galeria zdjęć', 'verbose_name_plural': 'Galeria zdjęć'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='chip_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='numer chip'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='identification_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='identyfikator'),
        ),
        migrations.AlterField(
            model_name='animalgallery',
            name='animal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shelter.Animal'),
        ),
        migrations.AlterField(
            model_name='animalgallery',
            name='photos',
            field=models.ImageField(upload_to=shelter.models.get_image_name, verbose_name='zdjęcia'),
        ),
    ]
