# Generated by Django 3.0.5 on 2020-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0012_auto_20200924_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adopted',
            field=models.BooleanField(default=True, verbose_name='adaptowany'),
        ),
    ]
