# Generated by Django 3.0.5 on 2020-10-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0013_animal_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adopted',
            field=models.BooleanField(default=False, verbose_name='adaptowany'),
        ),
    ]
