# Generated by Django 3.0.5 on 2020-10-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0014_auto_20201008_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='shelter_gallery', verbose_name='zdjęcie do galerii')),
            ],
        ),
    ]
