# Generated by Django 3.0.5 on 2020-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0015_sheltergallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterGalleryPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='gallery_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='sheltergallery',
            name='photo',
        ),
        migrations.AddField(
            model_name='sheltergallery',
            name='gallery_name',
            field=models.CharField(default='Galeria zdjęć', max_length=200),
        ),
    ]
