# Generated by Django 3.0.5 on 2020-10-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0016_auto_20201008_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheltergalleryphotos',
            name='gallery_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shelter.ShelterGallery'),
        ),
    ]
