# Generated by Django 3.0.5 on 2020-10-15 15:47

from django.db import migrations, models

import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0017_sheltergalleryphotos_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(upload_to=utils.utils.get_image_name, verbose_name='zdjęcie'),
        ),
    ]
