# Generated by Django 3.0.5 on 2020-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0018_auto_20201015_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalgallery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='sheltergallery',
            options={'verbose_name': 'Galeria zdjęć', 'verbose_name_plural': 'Galeria zdjęć'},
        ),
        migrations.AddField(
            model_name='animal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
