# Generated by Django 3.0.5 on 2020-10-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0020_auto_20201018_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petowner',
            name='animal',
            field=models.ForeignKey(db_constraint=False, db_index=False, help_text='Wybierz zwierzę które chcesz zaadaptować', on_delete=django.db.models.deletion.PROTECT, to='shelter.Animal', verbose_name='adoptowane zwiere'),
        ),
    ]
