# Generated by Django 3.0.5 on 2020-10-18 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0023_animal_adopted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.PetOwner'),
        ),
    ]
