# Generated by Django 3.0.5 on 2020-10-18 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0024_auto_20201018_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shelter.PetOwner'),
        ),
    ]
