# Generated by Django 3.0.5 on 2020-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('date', models.DateField(auto_now=True, verbose_name='data')),
                ('content', models.TextField(verbose_name='treść')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('img', models.ImageField(blank=True, upload_to='posts/', verbose_name='obrazek')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany')], default='draft', help_text='status publikacji', max_length=15, verbose_name='status')),
                ('facebook_id', models.CharField(default=0, max_length=250)),
            ],
        ),
    ]
