# Generated by Django 3.0.5 on 2020-08-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_post_id', models.CharField(default=0, max_length=250)),
                ('facebook_permalink_url', models.CharField(max_length=400, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='facebook_id',
        ),
    ]
