# Generated by Django 3.0.5 on 2020-08-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200814_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowany')], default='draft', help_text='status publikacji', max_length=15, verbose_name='status'),
        ),
    ]
