# Generated by Django 3.0.5 on 2020-08-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_facebookpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
