# Generated by Django 3.0.5 on 2020-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_facebookpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
