# Generated by Django 3.0.5 on 2020-10-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_facebookpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(blank=True, default=False, verbose_name='przypięty post'),
        ),
    ]
