# Generated by Django 3.0.5 on 2020-10-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20201015_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
