# Generated by Django 3.0.5 on 2020-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_postcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
