# Generated by Django 3.0.5 on 2020-10-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20201015_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='Topic',
        ),
    ]
