# Generated by Django 3.0.5 on 2020-10-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20201017_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookpost',
            options={'verbose_name': 'Facebook', 'verbose_name_plural': 'Facebook'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='content',
        ),
    ]
