# Generated by Django 3.0.5 on 2020-10-17 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0006_auto_20200930_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='email_title',
            field=models.CharField(default='Subscribe Email Template', max_length=250, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='emailbase',
            name='email_address',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Proszę podać prawidłowy adress.')]),
        ),
        migrations.AlterField(
            model_name='emailtemplates',
            name='email_body',
            field=models.TextField(blank=True, verbose_name='Treść'),
        ),
    ]
